KEYWORD_MAP = {
    "fever":              "fever",
    "high fever":         "high_fever",
    "mild fever":         "mild_fever",
    "temperature":        "fever",
    "headache":           "headache",
    "head ache":          "headache",
    "head pain":          "headache",
    "cough":              "cough",
    "dry cough":          "dry_cough",
    "cold":               "runny_nose",
    "runny nose":         "runny_nose",
    "blocked nose":       "nasal_congestion",
    "sore throat":        "sore_throat",
    "throat pain":        "sore_throat",
    "body ache":          "body_ache",
    "body pain":          "body_ache",
    "muscle pain":        "muscle_pain",
    "joint pain":         "joint_pain",
    "fatigue":            "fatigue",
    "tired":              "fatigue",
    "weakness":           "weakness",
    "nausea":             "nausea",
    "vomit":              "vomiting",
    "vomiting":           "vomiting",
    "diarrhea":           "diarrhoea",
    "diarrhoea":          "diarrhoea",
    "loose motion":       "diarrhoea",
    "stomach pain":       "abdominal_pain",
    "stomach ache":       "abdominal_pain",
    "abdominal pain":     "abdominal_pain",
    "chest pain":         "chest_pain",
    "breathless":         "breathlessness",
    "difficulty breathing":"breathlessness",
    "short of breath":    "breathlessness",
    "rash":               "skin_rash",
    "skin rash":          "skin_rash",
    "itching":            "itching",
    "itchy":              "itching",
    "jaundice":           "jaundice",
    "yellow skin":        "jaundice",
    "yellow eyes":        "jaundice",
    "dizziness":          "dizziness",
    "dizzy":              "dizziness",
    "loss of appetite":   "loss_of_appetite",
    "not eating":         "loss_of_appetite",
    "weight loss":        "weight_loss",
    "sweating":           "sweating",
    "excessive sweating": "excessive_sweating",
    "chills":             "chills",
    "shivering":          "chills",
    "back pain":          "back_pain",
    "burning urination":  "burning_urination",
    "frequent urination": "frequent_urination",
    "hair loss":          "hair_loss",
    "anxiety":            "anxiety",
    "depression":         "depression",
    "insomnia":           "insomnia",
    "sleep problems":     "insomnia",
    "constipation":       "constipation",
    "bloating":           "bloating",
    "heartburn":          "heartburn",
    "indigestion":        "indigestion",
    "swollen lymph":      "swollen_lymph_nodes",
    "night sweats":       "night_sweats",
    "loss of taste":      "loss_of_taste",
    "loss of smell":      "loss_of_smell",
    "red eyes":           "red_eyes",
    "eye pain":           "eye_pain",
    "ear pain":           "ear_pain",
    "stiff neck":         "stiff_neck",
    "sensitivity to light":"sensitivity_to_light",
}


def extract_symptoms(text: str) -> list:
    text_lower = text.lower()
    found = set()
    for phrase in sorted(KEYWORD_MAP.keys(), key=len, reverse=True):
        if phrase in text_lower:
            found.add(KEYWORD_MAP[phrase])

    return list(found)
